### ISSUE TITLE
Describe deployment method

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/gpms#5]
As the time of writing, it seems that @Huy-Ngo has drafted it.  Whether it's final or not, I'll let him decide and manage this issue accordingly.

One minor note though, quart-trio is a ASGI framework so hypercorn should be configured as such.  Regardless, we'll notice this once we really deploy the system :smile:

If appropriate, let's use this as the place to talk about how we'll push upstream changes to the actual server.  Python doesn't support hot swapping (at least not easily) so do we need to stop the running system before updating?  And how do we do that automatically *and* smoothly?

**Comment by Huy-Ngo** [comment]
Let's assume this is resolved via #11 until there are signs telling otherwise.

**Comment by Huy-Ngo** [comment]
This is not done yet. I haven't describe deployment for IPFS and RethinkDB

**Comment by McSinyx** [comment]
Cross-linking https://github.com/Huy-Ngo/gpms/pull/14#discussion_r523765553.

BTW did Dr Quang asked Dr @SonTG for a VM for us to play with (I don't get any email forwarded/CC'ed, maybe we should start a mailing list or something)?  That way it'd be much easier for figure out the exact deployment process.

**Comment by Huy-Ngo** [comment]
> BTW did Dr Quang asked Dr @SonTG for a VM for us to play with

Not that I'm aware of. I presume we will get one after the meeting next Tuesday.

**Comment by Huy-Ngo** [comment]
Before we're given one, though, here are my assumption:

- It's an Ubuntu server, probably 16.04 or 18.04.
- We might or might not get root access.
- Nothing described (other than systemd) is installed.

**Comment by McSinyx** [comment]
IIRC it'll be a VM, and I wish we can choose the OS.  NixOS would allow us to roll back (VM manager already allow this, but not *without* rebooting), plus almost everything is in its repo (including RethinkDB and IPFS).
